### ISSUE TITLE
emphasis to cd into nested folder

### ISSUE THREAD

**Issue by 13scoobie** [Nordstrom/hello-retail-workshop#25]
For the part referring to cloned repo ingress directory, maybe add a [code] section that has cd into directory 

https://github.com/Nordstrom/hello-retail-workshop/tree/master/Lesson1_HelloRetailStream#step-1-in-your-cloned-repo-go-to-the-ingress-stream-directory

**Comment by erikerikson** [comment]
resolved by https://github.com/Nordstrom/hello-retail-workshop/pull/39

Thanks @13scoobie !
