### ISSUE TITLE
What for fill into teamPolicy in private.yml

### ISSUE THREAD

**Issue by bikerp** [Nordstrom/hello-retail-workshop#60]
Hi,
I'm trying to deploy the Lesson 1 but I don't know what to fill into teamPolicy in private.yml.
Could you please explain what is it for?

Thanks

Pavel

**Comment by bikerp** [comment]
Hi, thank you for your answer. I leaved the `teamPolicy` property but the deployment failed during role creation. I is caused by the fact the `fanoutRole` must exist in IAM. What policies this role should have?

**Comment by gwsii** [comment]
@bikerp Did you get past this issue in your workshop?

**Comment by gwsii** [comment]
Great to hear! Closing the issue.
