### ISSUE TITLE
Add batch size to winner lambda yaml

### ISSUE THREAD

**Issue by RobGruhl** [Nordstrom/hello-retail-workshop#8]
batchSize: 100/200/1000?
We should make sure that the lambda is guaranteed to finish in a reasonable time.  Also may be more interesting to see many lambdas trigger in a flurry on cloudwatch than a single 1 minute long lambda.  Possible that the lambda just drains the log in no time at all...

**Comment by erikerikson** [comment]
Batch size is set:
```
          batchSize: 5
```
I believe that we can close this unless there's a good argument for bumping that batch size up.

**Comment by erikerikson** [comment]
here, to be specific:
https://github.com/Nordstrom/hello-retail-workshop/blob/master/Lesson2_CreateViewWithEventConsumer/winner-view/serverless.yml#L30

:D
